name: Code checks
run-name: Running code checks on ${{ github.actor }} pull request
on:
  pull_request:
    branches:
      - main
jobs:
  Ruff-checker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Running ruff code check and fix
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "check --fix"

      - name: Running ruff code format
        uses: astral-sh/ruff-action@v3
        with:
          src: "./src"
          args: "format"